apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermatic-dl
spec:
  selector:
    matchLabels:
      app: kubermatic-dl
  replicas: 1
  template:
    metadata:
      labels:
        app: kubermatic-dl
    spec:
     containers:
     - name: kubermatic-dl
       image: kubermatic00/kubermatic-dl:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubermatic-dl
  labels:
    app: kubermatic-dl
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: kubermatic-dl